export type ApiMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";

export type ApiCatalogItem = {
  id: string;
  module: string;
  name: string;
  method: ApiMethod;
  path: string;
  description: string;
  auth: string;
  params?: string[];
  body?: string[];
  response: string;
  curl: string;
  tags?: string[];
};

export const API_CATALOG: ApiCatalogItem[] = [
  {
    id: "overview-me",
    module: "Tổng quan",
    name: "Thông tin người dùng hiện tại",
    method: "GET",
    path: "/api/auth/me",
    description: "Lấy thông tin phiên đăng nhập để dựng trang tổng quan và phân quyền giao diện.",
    auth: "Bearer",
    response: '{"user":{"id":"...","email":"...","role":"admin"}}',
    curl: `curl -sS http://localhost:3000/api/auth/me -H 'Authorization: Bearer REDACTED'`,
    tags: ["auth", "overview"],
  },
  {
    id: "lead-list",
    module: "Khách hàng",
    name: "Danh sách khách hàng",
    method: "GET",
    path: "/api/leads",
    description: "Lọc, phân trang khách hàng theo trạng thái, owner, ngày tạo.",
    auth: "Bearer",
    params: ["page,pageSize", "status", "ownerId", "q", "createdFrom,createdTo"],
    response: '{"items":[{"id":"...","status":"HAS_PHONE"}],"total":120}',
    curl: `curl -sS 'http://localhost:3000/api/leads?page=1&pageSize=20&status=HAS_PHONE' -H 'Authorization: Bearer REDACTED'`,
    tags: ["lead", "crm"],
  },
  {
    id: "lead-create",
    module: "Khách hàng",
    name: "Tạo khách hàng",
    method: "POST",
    path: "/api/leads",
    description: "Tạo khách hàng mới, tự set trạng thái theo dữ liệu đầu vào.",
    auth: "Bearer",
    body: ["fullName", "phone", "source", "channel", "licenseType", "note", "tags[]"],
    response: '{"lead":{"id":"...","status":"NEW"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/leads -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"fullName":"Nguyen Van A","phone":"0900000000"}'`,
    tags: ["lead", "create"],
  },
  {
    id: "lead-update",
    module: "Khách hàng",
    name: "Cập nhật khách hàng",
    method: "PATCH",
    path: "/api/leads/{id}",
    description: "Cập nhật thông tin, trạng thái, owner và ghi log sự kiện liên quan.",
    auth: "Bearer",
    body: ["status", "ownerId", "fullName", "phone", "note", "tags[]"],
    response: '{"lead":{"id":"...","status":"SIGNED"}}',
    curl: `curl -sS -X PATCH http://localhost:3000/api/leads/REDACTED_ID -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"status":"APPOINTED"}'`,
    tags: ["lead", "update"],
  },
  {
    id: "lead-events",
    module: "Bảng trạng thái",
    name: "Ghi sự kiện khách hàng",
    method: "POST",
    path: "/api/leads/{id}/events",
    description: "Ghi event chuyển trạng thái hoặc event gọi để cập nhật pipeline.",
    auth: "Bearer",
    body: ["type", "note", "meta"],
    response: '{"event":{"id":"...","type":"CALLED"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/leads/REDACTED_ID/events -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"type":"CALLED","note":"Đã gọi"}'`,
    tags: ["pipeline", "event"],
  },
  {
    id: "kpi-daily",
    module: "KPI ngày",
    name: "KPI theo ngày",
    method: "GET",
    path: "/api/kpi/daily",
    description: "Tổng hợp KPI phần trăm theo ngày và lũy kế tháng (Asia/Ho_Chi_Minh).",
    auth: "Bearer",
    params: ["date=YYYY-MM-DD"],
    response:
      '{"date":"2026-02-16","directPage":{"hasPhoneRate":{"daily":{"valuePct":32.5}}},"tuVan":{"appointedRate":{"daily":{"valuePct":28.3}}}}',
    curl: `curl -sS 'http://localhost:3000/api/kpi/daily?date=2026-02-16' -H 'Authorization: Bearer REDACTED'`,
    tags: ["kpi", "daily"],
  },
  {
    id: "kpi-targets-list",
    module: "Mục tiêu KPI",
    name: "Danh sách mục tiêu KPI",
    method: "GET",
    path: "/api/kpi/targets",
    description: "Lấy mục tiêu KPI theo chi nhánh, vai trò và ngày trong tuần.",
    auth: "Bearer",
    params: ["branchId", "role=direct_page|telesales", "dayOfWeek=0..6", "ownerId", "activeOnly=true|false"],
    response: '{"items":[{"id":"...","metricKey":"appointed_rate_pct","targetValue":35}]}',
    curl: `curl -sS 'http://localhost:3000/api/kpi/targets?branchId=REDACTED_BRANCH&role=telesales&activeOnly=true' -H 'Authorization: Bearer REDACTED'`,
    tags: ["kpi", "target"],
  },
  {
    id: "kpi-targets-upsert",
    module: "Mục tiêu KPI",
    name: "Upsert mục tiêu KPI",
    method: "POST",
    path: "/api/kpi/targets",
    description: "Cập nhật mục tiêu KPI theo catalog chỉ số, có thể áp dụng theo vai trò hoặc theo nhân sự.",
    auth: "Bearer",
    body: ["branchId", "items[]: role, ownerId?, metricKey(catalog), targetValue, dayOfWeek?, isActive?"],
    response: '{"count":1,"items":[{"id":"...","metricKey":"appointed_rate_pct"}]}',
    curl: `curl -sS -X POST http://localhost:3000/api/kpi/targets -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"branchId":"REDACTED_BRANCH","items":[{"role":"telesales","metricKey":"appointed_rate_pct","targetValue":35}]}'`,
    tags: ["kpi", "target", "upsert"],
  },
  {
    id: "goals-list",
    module: "Mục tiêu ngày/tháng",
    name: "Danh sách mục tiêu ngày/tháng",
    method: "GET",
    path: "/api/goals",
    description: "Lấy mục tiêu doanh thu/hồ sơ/chi phí theo kỳ ngày hoặc tháng.",
    auth: "Bearer",
    params: ["periodType=DAILY|MONTHLY", "dateKey=YYYY-MM-DD", "monthKey=YYYY-MM", "branchId"],
    response: '{"items":[{"id":"...","periodType":"DAILY","revenueTarget":50000000}]}',
    curl: `curl -sS 'http://localhost:3000/api/goals?periodType=DAILY&dateKey=2026-02-16&branchId=REDACTED_BRANCH' -H 'Authorization: Bearer REDACTED'`,
    tags: ["goals", "daily", "monthly"],
  },
  {
    id: "goals-upsert",
    module: "Mục tiêu ngày/tháng",
    name: "Upsert mục tiêu ngày/tháng",
    method: "POST",
    path: "/api/goals",
    description: "Tạo/cập nhật mục tiêu theo kỳ và scope chi nhánh.",
    auth: "Bearer",
    body: ["periodType", "branchId?", "dateKey|monthKey", "revenueTarget", "dossierTarget", "costTarget", "note?"],
    response: '{"goal":{"id":"...","periodType":"MONTHLY","monthKey":"2026-02"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/goals -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"periodType":"MONTHLY","branchId":"REDACTED_BRANCH","monthKey":"2026-02","revenueTarget":1200000000,"dossierTarget":380,"costTarget":280000000}'`,
    tags: ["goals", "upsert"],
  },
  {
    id: "ai-suggestions-list",
    module: "Trợ lý công việc",
    name: "Danh sách gợi ý AI",
    method: "GET",
    path: "/api/ai/suggestions",
    description: "Lấy gợi ý công việc theo ngày, vai trò và phạm vi quyền.",
    auth: "Bearer",
    params: ["date=YYYY-MM-DD", "role", "branchId", "ownerId"],
    response:
      '{"items":[{"id":"...","scoreColor":"RED","title":"Tỷ lệ gọi thấp","feedbackStats":{"total":3,"helpful":2,"notHelpful":1,"done":0},"myFeedback":{"id":"...","feedbackType":"HELPFUL"}}]}',
    curl: `curl -sS 'http://localhost:3000/api/ai/suggestions?date=2026-02-16' -H 'Authorization: Bearer REDACTED'`,
    tags: ["ai", "kpi", "coach"],
  },
  {
    id: "ai-suggestions-create",
    module: "Trợ lý công việc",
    name: "Tạo gợi ý công việc thủ công",
    method: "POST",
    path: "/api/ai/suggestions",
    description: "Tạo gợi ý công việc thủ công để trưởng nhóm/admin theo dõi và áp dụng.",
    auth: "Bearer",
    body: ["dateKey", "role", "branchId?", "ownerId?", "title", "content", "scoreColor", "actionsJson?", "metricsJson?"],
    response: '{"suggestion":{"id":"...","status":"ACTIVE"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/ai/suggestions -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"dateKey":"2026-02-16","role":"telesales","title":"Cần gọi lại nhóm khách hẹn","content":"Ưu tiên nhóm lịch hẹn hôm qua","scoreColor":"YELLOW"}'`,
    tags: ["ai", "manual", "coach"],
  },
  {
    id: "ai-suggestions-feedback",
    module: "Trợ lý công việc",
    name: "Gửi phản hồi gợi ý AI",
    method: "POST",
    path: "/api/ai/suggestions/{id}/feedback",
    description: "Mỗi người dùng chỉ phản hồi 1 lần cho mỗi gợi ý. Hỗ trợ phản hồi hữu ích/không hữu ích/đã làm xong.",
    auth: "Bearer",
    body: ["feedbackType=HELPFUL|NOT_HELPFUL|DONE", "reason", "reasonDetail? (bắt buộc nếu reason='khac')", "note?", "actualResult? (data,hen,den,ky)"],
    response: '{"feedback":{"id":"...","feedbackType":"HELPFUL","reason":"de_lam_theo"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/ai/suggestions/REDACTED_ID/feedback -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"feedbackType":"HELPFUL","reason":"de_lam_theo","note":"Dễ áp dụng","actualResult":{"data":8,"hen":3}}'`,
    tags: ["ai", "feedback"],
  },
  {
    id: "ai-suggestions-ingest",
    module: "Trợ lý công việc",
    name: "Ingest gợi ý AI từ n8n",
    method: "POST",
    path: "/api/ai/suggestions/ingest",
    description: "Endpoint ingest service-token only, bắt buộc Idempotency-Key.",
    auth: "X-Service-Token + Idempotency-Key",
    body: ["source='n8n'", "runId", "suggestions[]: dateKey, role, scoreColor, title, content, actionsJson, metricsJson"],
    response: '{"ok":true,"count":2}',
    curl: `curl -sS -X POST http://localhost:3000/api/ai/suggestions/ingest -H 'x-service-token: REDACTED' -H 'Idempotency-Key: REDACTED-UUID' -H 'Content-Type: application/json' -d '{"source":"n8n","runId":"run-2026-02-16-1010","suggestions":[{"dateKey":"2026-02-16","role":"telesales","scoreColor":"RED","title":"Tỷ lệ gọi thấp","content":"Ưu tiên gọi lại nhóm HAS_PHONE"}]}'`,
    tags: ["ai", "ingest", "n8n"],
  },
  {
    id: "student-list",
    module: "Học viên",
    name: "Danh sách học viên",
    method: "GET",
    path: "/api/students",
    description: "Lấy danh sách học viên theo khóa học, trạng thái học, từ khóa.",
    auth: "Bearer",
    params: ["page,pageSize", "courseId", "studyStatus", "q"],
    response: '{"items":[{"id":"...","studyStatus":"studying"}],"total":45}',
    curl: `curl -sS 'http://localhost:3000/api/students?page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["student"],
  },
  {
    id: "student-create",
    module: "Học viên",
    name: "Tạo học viên từ khách hàng",
    method: "POST",
    path: "/api/students",
    description: "Nâng khách hàng thành học viên và gắn khóa học.",
    auth: "Bearer",
    body: ["leadId", "courseId", "studyStatus", "tuitionPlanId"],
    response: '{"student":{"id":"..."}}',
    curl: `curl -sS -X POST http://localhost:3000/api/students -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"leadId":"REDACTED_LEAD_ID"}'`,
    tags: ["student", "create"],
  },
  {
    id: "course-list",
    module: "Khóa học",
    name: "Danh sách khóa học",
    method: "GET",
    path: "/api/courses",
    description: "Lấy danh sách khóa học phục vụ quản trị học vụ.",
    auth: "Bearer",
    params: ["page,pageSize", "code", "province", "licenseType", "isActive"],
    response: '{"items":[{"id":"...","code":"B2-2026-01"}],"total":10}',
    curl: `curl -sS 'http://localhost:3000/api/courses?page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["course"],
  },
  {
    id: "course-create",
    module: "Khóa học",
    name: "Tạo khóa học",
    method: "POST",
    path: "/api/courses",
    description: "Tạo mới khóa học và cấu hình dữ liệu cơ bản.",
    auth: "Bearer",
    body: ["code", "province", "licenseType", "startDate", "examDate", "description"],
    response: '{"course":{"id":"...","code":"B2-2026-01"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/courses -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"code":"B2-2026-01"}'`,
    tags: ["course", "create"],
  },
  {
    id: "schedule-list",
    module: "Lịch học",
    name: "Danh sách lịch học",
    method: "GET",
    path: "/api/schedule",
    description: "Lấy lịch học theo ngày, khóa học, trạng thái và tìm kiếm học viên.",
    auth: "Bearer",
    params: ["from,to", "courseId", "status", "q", "location", "page,pageSize"],
    response: '{"items":[{"id":"...","title":"Lịch học thủ công","meta":{"status":"PLANNED"}}],"total":6}',
    curl: `curl -sS 'http://localhost:3000/api/schedule?from=2026-02-16&to=2026-02-16' -H 'Authorization: Bearer REDACTED'`,
    tags: ["schedule", "list"],
  },
  {
    id: "schedule-create",
    module: "Lịch học",
    name: "Tạo lịch học thủ công",
    method: "POST",
    path: "/api/schedule",
    description: "Tạo lịch theo course hoặc student, có check trùng giờ và cho phép admin override bằng allowOverlap. Bắt buộc Idempotency-Key.",
    auth: "Bearer",
    body: ["courseId | studentId", "startAt", "endAt", "location", "note", "status", "allowOverlap"],
    response: '{"item":{"id":"...","source":"MANUAL","status":"PLANNED"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/schedule -H 'Authorization: Bearer REDACTED' -H 'Idempotency-Key: REDACTED-UUID' -H 'Content-Type: application/json' -d '{"courseId":"REDACTED_COURSE_ID","startAt":"2026-02-16T08:00:00+07:00","status":"planned"}'`,
    tags: ["schedule", "manual"],
  },
  {
    id: "receipt-list",
    module: "Thu tiền",
    name: "Danh sách phiếu thu",
    method: "GET",
    path: "/api/receipts",
    description: "Lấy danh sách phiếu thu theo học viên, ngày, phương thức.",
    auth: "Bearer",
    params: ["page,pageSize", "studentId", "date|from,to", "method", "q"],
    response: '{"items":[{"id":"...","amount":5000000}],"total":30}',
    curl: `curl -sS 'http://localhost:3000/api/receipts?page=1&pageSize=20&from=2026-02-01&to=2026-02-16' -H 'Authorization: Bearer REDACTED'`,
    tags: ["receipt", "finance"],
  },
  {
    id: "receipt-create",
    module: "Thu tiền",
    name: "Tạo phiếu thu",
    method: "POST",
    path: "/api/receipts",
    description: "Ghi nhận thu tiền cho học viên. Bắt buộc Idempotency-Key.",
    auth: "Bearer",
    body: ["studentId", "amount", "method", "receivedAt", "note"],
    response: '{"receipt":{"id":"...","amount":3000000}}',
    curl: `curl -sS -X POST http://localhost:3000/api/receipts -H 'Authorization: Bearer REDACTED' -H 'Idempotency-Key: REDACTED-UUID' -H 'Content-Type: application/json' -d '{"studentId":"REDACTED_STUDENT_ID","amount":3000000,"method":"cash"}'`,
    tags: ["receipt", "create"],
  },
  {
    id: "outbound-dispatch",
    module: "Gửi tin",
    name: "Chạy dispatch outbound",
    method: "POST",
    path: "/api/outbound/dispatch",
    description: "Đẩy batch outbound qua worker. Bắt buộc Idempotency-Key.",
    auth: "Bearer",
    body: ["limit", "retryFailedOnly"],
    response: '{"total":20,"accepted":18,"failed":2}',
    curl: `curl -sS -X POST http://localhost:3000/api/outbound/dispatch -H 'Authorization: Bearer REDACTED' -H 'Idempotency-Key: REDACTED-UUID' -H 'Content-Type: application/json' -d '{"limit":20}'`,
    tags: ["outbound", "dispatch"],
  },
  {
    id: "outbound-jobs-create",
    module: "Gửi tin",
    name: "Tạo outbound job từ action AI",
    method: "POST",
    path: "/api/outbound/jobs",
    description: "Tạo job outbound an toàn từ UI action, bắt buộc Idempotency-Key.",
    auth: "Bearer",
    body: ["channel", "templateKey", "leadId|studentId", "to?", "priority?", "variables?", "note?", "suggestionId?", "actionKey?", "taskId?"],
    response: '{"outboundMessage":{"id":"...","status":"QUEUED"},"outboundJob":{"id":"...","metaJson":{"actionKey":"CREATE_OUTBOUND_JOB"}}}',
    curl: `curl -sS -X POST http://localhost:3000/api/outbound/jobs -H 'Authorization: Bearer REDACTED' -H 'Idempotency-Key: REDACTED-UUID' -H 'Content-Type: application/json' -d '{"channel":"CALL_NOTE","templateKey":"remind_schedule","leadId":"REDACTED_LEAD","suggestionId":"REDACTED_SUGGESTION_ID","actionKey":"CREATE_OUTBOUND_JOB"}'`,
    tags: ["outbound", "ai-action", "idempotency", "goi-nhac"],
  },
  {
    id: "outbound-jobs-status-patch",
    module: "Gửi tin",
    name: "n8n cập nhật trạng thái danh sách gọi",
    method: "PATCH",
    path: "/api/outbound/jobs/:id",
    description: "n8n cập nhật trạng thái xử lý job gọi nhắc (service token + Idempotency-Key).",
    auth: "x-service-token (SERVICE_TOKEN)",
    body: ["status=NEW|DISPATCHED|DONE|FAILED", "runId?", "lastError?"],
    response: '{"ok":true,"job":{"id":"...","status":"DONE"}}',
    curl: `curl -sS -X PATCH http://localhost:3000/api/outbound/jobs/REDACTED_JOB_ID -H 'x-service-token: REDACTED' -H 'Idempotency-Key: REDACTED-UUID' -H 'Content-Type: application/json' -d '{"status":"DONE","runId":"run-2026-02-16-01"}'`,
    tags: ["outbound", "n8n", "status"],
  },
  {
    id: "notifications-list",
    module: "Thông báo",
    name: "Danh sách thông báo",
    method: "GET",
    path: "/api/notifications",
    description: "Lấy danh sách việc cần làm theo scope và trạng thái.",
    auth: "Bearer",
    params: ["status", "scope", "page,pageSize"],
    response: '{"items":[{"id":"...","title":"Nhắc thu tiền"}],"total":15}',
    curl: `curl -sS 'http://localhost:3000/api/notifications?status=NEW&page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["notification"],
  },
  {
    id: "tasks-list",
    module: "Thông báo",
    name: "Danh sách việc cần làm (Tasks)",
    method: "GET",
    path: "/api/tasks",
    description: "Alias API việc cần làm để tích hợp ngoài hệ thống, map về Notification.",
    auth: "Bearer",
    params: ["status", "scope", "from,to", "q", "suggestionId", "page,pageSize"],
    response: '{"items":[{"id":"...","title":"Nhắc thu tiền","status":"NEW"}],"page":1,"pageSize":20,"total":12}',
    curl: `curl -sS 'http://localhost:3000/api/tasks?status=NEW&page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["task", "notification", "automation"],
  },
  {
    id: "tasks-create",
    module: "Thông báo",
    name: "Tạo việc cần làm (Tasks)",
    method: "POST",
    path: "/api/tasks",
    description: "Tạo việc cần làm thủ công hoặc từ automation n8n.",
    auth: "Bearer",
    body: ["title", "message", "scope?", "priority?", "type=TASK|REMINDER|CALL_LIST", "suggestionId?", "actionKey?", "ownerId?", "leadId?", "studentId?", "dueAt?", "payload?"],
    response: '{"task":{"id":"...","status":"NEW"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/tasks -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"title":"Gọi lại khách hẹn","message":"Ưu tiên xử lý trước 16h","scope":"FOLLOWUP","priority":"HIGH","type":"TASK","suggestionId":"REDACTED_SUGGESTION_ID","actionKey":"CREATE_TASK"}'`,
    tags: ["task", "create", "automation", "ai-apply"],
  },
  {
    id: "outbound-list",
    module: "Gửi tin",
    name: "Danh sách outbound",
    method: "GET",
    path: "/api/outbound/messages",
    description: "Lấy danh sách hàng đợi outbound để theo dõi tiến trình gửi.",
    auth: "Bearer",
    params: ["status", "channel", "from,to", "page,pageSize"],
    response: '{"items":[{"id":"...","status":"QUEUED"}],"total":30}',
    curl: `curl -sS 'http://localhost:3000/api/outbound/messages?status=QUEUED&page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["outbound", "list"],
  },
  {
    id: "outbound-messages",
    module: "Gửi tin",
    name: "Danh sách/tạo tin outbound",
    method: "POST",
    path: "/api/outbound/messages",
    description: "Đẩy tin nhắn ra hàng đợi outbound theo template.",
    auth: "Bearer",
    body: ["channel", "templateKey", "leadId|studentId", "priority", "to"],
    response: '{"item":{"id":"...","status":"QUEUED"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/outbound/messages -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"channel":"ZALO","templateKey":"remind.study"}'`,
    tags: ["outbound", "queue"],
  },
  {
    id: "my-payroll",
    module: "Lương tôi",
    name: "Phiếu lương cá nhân",
    method: "GET",
    path: "/api/me/payroll",
    description: "Lấy bảng lương theo tháng của người dùng hiện tại.",
    auth: "Bearer",
    params: ["month=YYYY-MM"],
    response: '{"items":[{"month":"2026-02","totalVnd":15000000}]}',
    curl: `curl -sS 'http://localhost:3000/api/me/payroll?month=2026-02' -H 'Authorization: Bearer REDACTED'`,
    tags: ["payroll", "me"],
  },
  {
    id: "ops-pulse",
    module: "AI hỗ trợ nhân sự",
    name: "Danh sách Ops Pulse",
    method: "GET",
    path: "/api/admin/ops/pulse",
    description: "Xem snapshot cảnh báo và gợi ý ưu tiên theo role/owner/dateKey.",
    auth: "Bearer (admin)",
    params: ["role", "ownerId", "dateKey", "limit"],
    response: '{"items":[{"id":"...","role":"PAGE","dateKey":"2026-02-16"}]}',
    curl: `curl -sS 'http://localhost:3000/api/admin/ops/pulse?dateKey=2026-02-16&limit=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["ops", "ai"],
  },
  {
    id: "n8n-workflows",
    module: "Luồng n8n",
    name: "Danh sách workflow n8n",
    method: "GET",
    path: "/api/admin/n8n/workflows",
    description: "Trả về tài liệu workflow n8n để hiển thị cho admin.",
    auth: "Bearer (admin)",
    response: '{"overview":"...","workflows":[{"id":"wf-1","name":"..."}]}',
    curl: `curl -sS http://localhost:3000/api/admin/n8n/workflows -H 'Authorization: Bearer REDACTED'`,
    tags: ["n8n", "docs"],
  },
  {
    id: "admin-automation-overview",
    module: "Luồng n8n",
    name: "Tổng quan giám sát luồng tự động",
    method: "GET",
    path: "/api/admin/automation/overview",
    description: "Lấy số liệu tổng quan job và log theo ngày (múi giờ Asia/Ho_Chi_Minh).",
    auth: "Bearer (admin)",
    params: ["date=YYYY-MM-DD"],
    response: '{"dateKey":"2026-02-16","jobs":{"today":{"NEW":3,"DISPATCHED":5,"DONE":12,"FAILED":1}}}',
    curl: `curl -sS 'http://localhost:3000/api/admin/automation/overview?date=2026-02-16' -H 'Authorization: Bearer REDACTED'`,
    tags: ["automation", "monitor"],
  },
  {
    id: "admin-automation-jobs",
    module: "Luồng n8n",
    name: "Danh sách OutboundJob giám sát",
    method: "GET",
    path: "/api/admin/automation/jobs",
    description: "Lấy danh sách việc gọi nhắc gần đây, hỗ trợ lọc theo ngày, chi nhánh, trạng thái, kênh, runId.",
    auth: "Bearer (admin)",
    params: ["date=YYYY-MM-DD", "status?", "branchId?", "channel?", "runId?", "limit<=200"],
    response: '{"items":[{"id":"...","status":"DONE","runId":"run-..." }],"total":20}',
    curl: `curl -sS 'http://localhost:3000/api/admin/automation/jobs?date=2026-02-16&status=FAILED&limit=50' -H 'Authorization: Bearer REDACTED'`,
    tags: ["automation", "jobs", "monitor"],
  },
  {
    id: "admin-automation-errors",
    module: "Luồng n8n",
    name: "Top lỗi OutboundJob",
    method: "GET",
    path: "/api/admin/automation/errors",
    description: "Thống kê lỗi nổi bật từ job FAILED trong ngày.",
    auth: "Bearer (admin)",
    params: ["date=YYYY-MM-DD", "limit<=50"],
    response: '{"items":[{"message":"...","count":3,"lastSeenAt":"2026-02-16T09:00:00.000Z"}]}',
    curl: `curl -sS 'http://localhost:3000/api/admin/automation/errors?date=2026-02-16&limit=5' -H 'Authorization: Bearer REDACTED'`,
    tags: ["automation", "errors", "monitor"],
  },
  {
    id: "admin-automation-logs",
    module: "Luồng n8n",
    name: "Nhật ký chi tiết theo runId/suggestion",
    method: "GET",
    path: "/api/admin/automation/logs",
    description: "Lấy log chi tiết theo ngày, milestone, runId, suggestionId, outboundJobId.",
    auth: "Bearer (admin)",
    params: ["date=YYYY-MM-DD", "milestone?", "branchId?", "runId?", "suggestionId?", "outboundJobId?", "limit<=300"],
    response: '{"items":[{"id":"...","milestone":"outbound-job-status","status":"sent"}],"total":8}',
    curl: `curl -sS 'http://localhost:3000/api/admin/automation/logs?date=2026-02-16&runId=run-2026-02-16-01&limit=100' -H 'Authorization: Bearer REDACTED'`,
    tags: ["automation", "logs", "monitor"],
  },
  {
    id: "automation-logs",
    module: "Tự động hóa - Nhật ký",
    name: "Nhật ký chạy tự động hóa",
    method: "GET",
    path: "/api/automation/logs",
    description: "Lấy log chạy theo scope, trạng thái, ngày.",
    auth: "Bearer",
    params: ["scope", "status", "from,to", "page,pageSize"],
    response: '{"items":[{"id":"...","status":"sent"}],"total":100}',
    curl: `curl -sS 'http://localhost:3000/api/automation/logs?scope=daily&page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["automation", "logs"],
  },
  {
    id: "automation-logs-create",
    module: "Tự động hóa - Nhật ký",
    name: "Ghi nhật ký tự động hóa",
    method: "POST",
    path: "/api/automation/logs",
    description: "Ghi log tác vụ tự động hóa thủ công hoặc từ quy trình ngoài.",
    auth: "Bearer",
    body: ["channel", "milestone?", "status?", "branchId?", "leadId?", "studentId?", "templateKey?", "payload?"],
    response: '{"log":{"id":"...","status":"sent"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/automation/logs -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"channel":"TASK","milestone":"n8n.manual","status":"sent","payload":{"note":"ghi log test"}}'`,
    tags: ["automation", "logs", "create"],
  },
  {
    id: "automation-logs-ingest",
    module: "Tự động hóa - Nhật ký",
    name: "n8n đẩy log vận hành",
    method: "POST",
    path: "/api/automation/logs/ingest",
    description: "Ingest log từ n8n bằng service token, bắt buộc Idempotency-Key.",
    auth: "x-service-token (SERVICE_TOKEN)",
    body: ["branchId", "channel", "status=sent|skipped|failed", "milestone?", "leadId?", "studentId?", "templateKey?", "payload?"],
    response: '{"ok":true,"log":{"id":"...","status":"sent"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/automation/logs/ingest -H 'x-service-token: REDACTED' -H 'Idempotency-Key: REDACTED-UUID' -H 'Content-Type: application/json' -d '{"branchId":"REDACTED_BRANCH","channel":"n8n","status":"sent","milestone":"w7.apply","payload":{"runId":"run-2026-02-16-01"}}'`,
    tags: ["automation", "logs", "ingest", "n8n"],
  },
  {
    id: "automation-run",
    module: "Tự động hóa - Chạy tay",
    name: "Chạy tác vụ tự động hóa",
    method: "POST",
    path: "/api/automation/run",
    description: "Chạy tay workflow tự động hóa theo scope daily/manual.",
    auth: "Bearer (admin)",
    body: ["scope", "leadId", "studentId", "dryRun"],
    response: '{"log":{"id":"...","status":"sent"}}',
    curl: `curl -sS -X POST http://localhost:3000/api/automation/run -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"scope":"daily","dryRun":true}'`,
    tags: ["automation", "run"],
  },
  {
    id: "marketing-report",
    module: "Báo cáo Meta Ads",
    name: "Báo cáo marketing theo ngày",
    method: "GET",
    path: "/api/admin/marketing/reports",
    description: "Lấy báo cáo chi phí/tin nhắn/CPL theo nguồn và ngày.",
    auth: "Bearer (admin)",
    params: ["from,to", "branchId", "source", "page,pageSize"],
    response: '{"items":[{"dateKey":"2026-02-16","spendVnd":2000000,"messages":100}],"total":1}',
    curl: `curl -sS 'http://localhost:3000/api/admin/marketing/reports?from=2026-02-01&to=2026-02-16&source=meta' -H 'Authorization: Bearer REDACTED'`,
    tags: ["marketing", "meta"],
  },
  {
    id: "branches",
    module: "Chi nhánh",
    name: "Danh sách/tạo chi nhánh",
    method: "GET",
    path: "/api/admin/branches",
    description: "Quản trị danh sách chi nhánh hoạt động.",
    auth: "Bearer (admin)",
    response: '{"items":[{"id":"...","name":"CN Quận 1"}],"total":3}',
    curl: `curl -sS 'http://localhost:3000/api/admin/branches?page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["branch", "admin"],
  },
  {
    id: "admin-users",
    module: "Người dùng",
    name: "Danh sách/tạo người dùng",
    method: "GET",
    path: "/api/admin/users",
    description: "Quản lý tài khoản và phân quyền người dùng hệ thống.",
    auth: "Bearer (admin)",
    params: ["q", "role", "isActive", "branchId", "page,pageSize"],
    response: '{"items":[{"id":"...","email":"admin@...","role":"admin"}],"total":12}',
    curl: `curl -sS 'http://localhost:3000/api/admin/users?page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["user", "admin"],
  },
  {
    id: "assign-leads",
    module: "Phân khách hàng",
    name: "Phân khách hàng thủ công",
    method: "POST",
    path: "/api/leads/assign",
    description: "Gán danh sách khách hàng cho một owner và ghi LeadEvent.",
    auth: "Bearer (admin)",
    body: ["leadIds[]", "ownerId"],
    response: '{"updated":12}',
    curl: `curl -sS -X POST http://localhost:3000/api/leads/assign -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"ownerId":"REDACTED_USER_ID","leadIds":["REDACTED_LEAD_ID"]}'`,
    tags: ["assign", "lead"],
  },
  {
    id: "tuition-plans",
    module: "Bảng học phí",
    name: "Danh sách/tạo bảng học phí",
    method: "GET",
    path: "/api/tuition-plans",
    description: "Quản trị bảng học phí theo tỉnh/hạng bằng.",
    auth: "Bearer",
    params: ["province", "licenseType", "isActive", "page,pageSize"],
    response: '{"items":[{"id":"...","province":"HCM","licenseType":"B2"}],"total":8}',
    curl: `curl -sS 'http://localhost:3000/api/tuition-plans?page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["tuition", "plan"],
  },
  {
    id: "notifications-generate",
    module: "Quản trị thông báo",
    name: "Sinh thông báo tự động",
    method: "POST",
    path: "/api/notifications/generate",
    description: "Sinh thông báo theo scope nghiệp vụ (ví dụ tài chính).",
    auth: "Bearer",
    body: ["scope", "dryRun"],
    response: '{"created":10,"preview":[...]}',
    curl: `curl -sS -X POST http://localhost:3000/api/notifications/generate -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"scope":"finance","dryRun":true}'`,
    tags: ["notification", "generate"],
  },
  {
    id: "cron-daily",
    module: "Vận hành tự động",
    name: "Chạy cron hằng ngày",
    method: "POST",
    path: "/api/admin/cron/daily",
    description: "Kích hoạt luồng tự động theo ngày từ trang vận hành.",
    auth: "Bearer (admin)",
    body: ["dryRun", "force"],
    response: '{"ok":true,"counts":{"notificationsCreated":0}}',
    curl: `curl -sS -X POST http://localhost:3000/api/admin/cron/daily -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"dryRun":true}'`,
    tags: ["cron", "automation"],
  },
  {
    id: "worker-outbound",
    module: "Tiến trình gửi tin",
    name: "Chạy worker outbound",
    method: "POST",
    path: "/api/admin/worker/outbound",
    description: "Chạy worker gửi tin và trả kết quả tổng hợp sent/failed/skipped.",
    auth: "Bearer (admin)",
    body: ["batchSize", "dryRun"],
    response: '{"ok":true,"result":{"sent":5,"failed":0}}',
    curl: `curl -sS -X POST http://localhost:3000/api/admin/worker/outbound -H 'Authorization: Bearer REDACTED' -H 'Content-Type: application/json' -d '{"batchSize":20,"dryRun":true}'`,
    tags: ["worker", "outbound"],
  },
  {
    id: "scheduler-health",
    module: "Lập lịch",
    name: "Kiểm tra sức khỏe scheduler",
    method: "GET",
    path: "/api/admin/scheduler/health",
    description: "Theo dõi độ trễ và cảnh báo của scheduler/queue.",
    auth: "Bearer (admin)",
    response: '{"summary":{"status":"ok"},"queues":[]}',
    curl: `curl -sS http://localhost:3000/api/admin/scheduler/health -H 'Authorization: Bearer REDACTED'`,
    tags: ["scheduler", "health"],
  },
  {
    id: "student-content",
    module: "Nội dung học viên",
    name: "Danh sách/tạo nội dung học viên",
    method: "GET",
    path: "/api/admin/student-content",
    description: "Quản trị nội dung cho cổng học viên.",
    auth: "Bearer (admin)",
    params: ["category", "isPublished", "page,pageSize"],
    response: '{"items":[{"id":"...","title":"Hướng dẫn hồ sơ"}],"total":12}',
    curl: `curl -sS 'http://localhost:3000/api/admin/student-content?page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["content", "student"],
  },
  {
    id: "employee-kpi",
    module: "KPI nhân sự",
    name: "Danh sách/tạo KPI nhân sự",
    method: "GET",
    path: "/api/admin/employee-kpi",
    description: "Thiết lập chỉ tiêu KPI theo vai trò và thời gian hiệu lực.",
    auth: "Bearer (admin)",
    params: ["userId", "role", "isActive", "page,pageSize"],
    response: '{"items":[{"id":"...","role":"PAGE"}],"total":6}',
    curl: `curl -sS 'http://localhost:3000/api/admin/employee-kpi?page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["hr", "kpi"],
  },
  {
    id: "salary-profiles",
    module: "Hồ sơ lương",
    name: "Danh sách/tạo hồ sơ lương",
    method: "GET",
    path: "/api/admin/salary-profiles",
    description: "Quản trị hồ sơ lương theo nhân sự và chi nhánh.",
    auth: "Bearer (admin)",
    params: ["userId", "branchId", "month", "page,pageSize"],
    response: '{"items":[{"id":"...","baseSalaryVnd":12000000}],"total":20}',
    curl: `curl -sS 'http://localhost:3000/api/admin/salary-profiles?page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["hr", "salary"],
  },
  {
    id: "attendance",
    module: "Chấm công",
    name: "Danh sách/tạo chấm công",
    method: "GET",
    path: "/api/admin/attendance",
    description: "Quản lý dữ liệu chấm công theo tháng, user, chi nhánh.",
    auth: "Bearer (admin)",
    params: ["month", "userId", "branchId", "page,pageSize"],
    response: '{"items":[{"id":"...","status":"PRESENT"}],"total":50}',
    curl: `curl -sS 'http://localhost:3000/api/admin/attendance?month=2026-02&page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["hr", "attendance"],
  },
  {
    id: "payroll-total",
    module: "Tổng lương",
    name: "Danh sách kỳ lương",
    method: "GET",
    path: "/api/admin/payroll",
    description: "Lấy danh sách payroll run và tổng lương theo kỳ/chi nhánh.",
    auth: "Bearer (admin)",
    params: ["month", "branchId", "page,pageSize"],
    response: '{"items":[{"id":"...","status":"DRAFT","items":[{"totalVnd":15000000}]}],"total":1}',
    curl: `curl -sS 'http://localhost:3000/api/admin/payroll?month=2026-02&page=1&pageSize=20' -H 'Authorization: Bearer REDACTED'`,
    tags: ["payroll", "total"],
  },
  {
    id: "expenses-daily",
    module: "Thu tiền",
    name: "Chi phí theo ngày",
    method: "GET",
    path: "/api/expenses/daily",
    description: "Lấy chi phí theo danh mục của một ngày theo scope chi nhánh.",
    auth: "Bearer",
    params: ["date=YYYY-MM-DD", "branchId (admin)"],
    response: '{"branchId":"...","dateKey":"2026-02-16","items":[{"categoryName":"Mặt bằng","amountVnd":1500000}]}',
    curl: `curl -sS 'http://localhost:3000/api/expenses/daily?date=2026-02-16' -H 'Authorization: Bearer REDACTED'`,
    tags: ["expenses", "daily"],
  },
  {
    id: "expenses-summary",
    module: "Thu tiền",
    name: "Tổng hợp chi phí tháng",
    method: "GET",
    path: "/api/expenses/summary",
    description: "Tổng hợp theo danh mục + lương cơ bản + tổng chi tháng.",
    auth: "Bearer",
    params: ["month=YYYY-MM", "branchId (admin)"],
    response: '{"monthKey":"2026-02","expensesTotalVnd":0,"baseSalaryTotalVnd":0,"grandTotalVnd":0}',
    curl: `curl -sS 'http://localhost:3000/api/expenses/summary?month=2026-02' -H 'Authorization: Bearer REDACTED'`,
    tags: ["expenses", "summary"],
  },
  {
    id: "expenses-base-salary",
    module: "Tổng lương",
    name: "Drilldown lương cơ bản",
    method: "GET",
    path: "/api/expenses/base-salary",
    description: "Lấy và cập nhật lương cơ bản theo user/chi nhánh/tháng.",
    auth: "Bearer",
    params: ["month=YYYY-MM", "branchId (admin)"],
    response: '{"monthKey":"2026-02","rows":[{"userId":"...","baseSalaryVnd":12000000}]}',
    curl: `curl -sS 'http://localhost:3000/api/expenses/base-salary?month=2026-02' -H 'Authorization: Bearer REDACTED'`,
    tags: ["expenses", "salary"],
  },
  {
    id: "insights-expenses",
    module: "AI hỗ trợ nhân sự",
    name: "Danh sách insight chi phí",
    method: "GET",
    path: "/api/insights/expenses",
    description: "Lấy insight chi phí theo tháng/ngày trong phạm vi quyền.",
    auth: "Bearer",
    params: ["month=YYYY-MM", "date=YYYY-MM-DD", "branchId (admin)"],
    response: '{"items":[{"id":"...","summary":"Chi phí tăng 8%"}]}',
    curl: `curl -sS 'http://localhost:3000/api/insights/expenses?month=2026-02' -H 'Authorization: Bearer REDACTED'`,
    tags: ["insights", "expenses"],
  },
  {
    id: "insights-expenses-ingest",
    module: "AI hỗ trợ nhân sự",
    name: "Ingest insight chi phí (service token)",
    method: "POST",
    path: "/api/insights/expenses/ingest",
    description: "Nhận insight từ n8n qua service token, không dùng JWT người dùng. Bắt buộc source=n8n, runId và Idempotency-Key.",
    auth: "x-service-token",
    body: ["branchCode|branchId", "dateKey", "monthKey", "summary", "payloadJson", "source=n8n", "runId"],
    response: '{"ok":true,"item":{"id":"..."}}',
    curl: `curl -sS -X POST http://localhost:3000/api/insights/expenses/ingest -H 'x-service-token: REDACTED' -H 'Idempotency-Key: REDACTED-UUID' -H 'Content-Type: application/json' -d '{"branchCode":"Q1","dateKey":"2026-02-16","monthKey":"2026-02","source":"n8n","runId":"run-2026-02-16-001","summary":"Chi phí tăng 8%"}'`,
    tags: ["insights", "ingest", "n8n"],
  },
];
