export const MODULE_KEYS = [
  "overview",
  "leads",
  "leads_board",
  "kpi_daily",
  "kpi_targets",
  "goals",
  "ai_kpi_coach",
  "ai_suggestions",
  "students",
  "courses",
  "schedule",
  "receipts",
  "notifications",
  "outbound_jobs",
  "messaging",
  "my_payroll",
  "ops_ai_hr",
  "ops_n8n",
  "automation_logs",
  "automation_run",
  "marketing_meta_ads",
  "admin_branches",
  "admin_users",
  "admin_segments",
  "admin_tuition",
  "admin_notification_admin",
  "admin_automation_admin",
  "admin_send_progress",
  "admin_plans",
  "admin_student_content",
  "admin_instructors",
  "hr_kpi",
  "hr_payroll_profiles",
  "hr_attendance",
  "hr_total_payroll",
  "api_hub",
  "expenses",
  "salary",
  "insights",
  "admin_tracking",
] as const;

export const ACTION_KEYS = ["VIEW", "CREATE", "UPDATE", "FEEDBACK", "EDIT", "DELETE", "EXPORT", "ASSIGN", "RUN", "INGEST"] as const;

export type ModuleKey = (typeof MODULE_KEYS)[number];
export type ActionKey = (typeof ACTION_KEYS)[number];
